name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:18.3
        env:
          POSTGRES_DB: raccoonbets_test
          POSTGRES_USER: raccoonbets
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - "5432:5432"
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - "6379:6379"
    steps:
      - uses: actions/checkout@v6
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - name: Create test database
        env:
          POSTGRES_DB: raccoonbets_test
          POSTGRES_USER: raccoonbets
          POSTGRES_PASSWORD: postgres
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          RAILS_ENV: test
        run: |
          sudo apt-get install libpq-dev
          bin/rails db:setup
      - name: Run unit tests
        env:
          POSTGRES_DB: raccoonbets_test
          POSTGRES_USER: raccoonbets
          POSTGRES_PASSWORD: postgres
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: bundle exec rspec spec

  lint:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - name: Run Rubocop
        run: |
          gem install rubocop-rails rubocop-rspec rubocop-performance rubocop-md rubocop-rake \
            rubocop-graphql rubocop-rspec_rails rubocop-sidekiq rubocop-yard rubocop-factory_bot
          curl https://gist.githubusercontent.com/RISCfuture/65e21b9e8b0d1db285dcb4fc627b98fa/raw/.rubocop.yml \
            > .rubocop-ruby.yml
          curl -O https://gist.githubusercontent.com/RISCfuture/14cfa24d53c12bf385871e9b93b95c37/raw/.rubocop-rspec.yml
          curl -O https://gist.githubusercontent.com/RISCfuture/9f3bb94ef794f92dd480cffa019e91a4/raw/.rubocop-rails.yml
          cat .rubocop.yml | sed -e 's/~\/.rubocop/.rubocop/' | sed -e 's/.rubocop.yml/.rubocop-ruby.yml/' \
            > .rubocop2.yml
          mv .rubocop2.yml .rubocop.yml
          rubocop --parallel -f github
      - name: Run Brakeman
        run: bin/brakeman --no-pager
